import { Rubik } from "next/font/google";
import "./globals.css";

const rubikSans = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${rubikSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
